// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserRequest struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	Hobby       string `json:"hobby"`
	PhoneNumber string `json:"phone_number"`
	Address     string `json:"address"`
	Dob         string `json:"dob"`
	Avatar      string `json:"avatar"`
}

type User struct {
	ID          string `json:"id"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	Hobby       string `json:"hobby"`
	PhoneNumber string `json:"phone_number"`
	Address     string `json:"address"`
	Dob         string `json:"dob"`
	Avatar      string `json:"avatar"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	DeletedAt   string `json:"deleted_at"`
}
